# Generated by Django 5.0.4 on 2024-05-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('Carrera', models.CharField(max_length=50)),
                ('creditos', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
